# # python calc.py tps_clc/nontaxablecombsatpay.clc
mapping = {
    "FFIT161.ESTBOX": "Estate",
    "FFIT161.TRUSBOX": "Trust",
    "FFIT161.RTRUST": "RevocableTrust",
    "FFIT161.ITRUST": "IrrevocableTrust",
    "FFIT161.EXTENBX": "ExtendedRtn",
    "FFIT161.AMENDX": "AmendedRtn",
    "FFIT161.FINALBX": "FinalRtn",
    "FFIT161.FDOB": "DateOfDeath",
    "FFIT161.NRBENY": "NonResdeBenef",
    "FFIT161.MUNIINCY": "NoVtMuni",
    "FFIT161.SKIPY": "PresFutBenSkip",
    "FFIT161.QSFYES": "QualSettleFnd",
    "FFIT161.FTAXINC": "FederalTaxableIncome",
    "FFIT161.NONVTINC": "NonVtIncome",
    "FFIT161.BONUS": "BonusDepreciation",
    "FFIT161.OVER5K": "StateLocalTaxesOv5k",
    "FFIT161.INCWADD": "FedTaxableWithAdd",
    "FFIT161.INTERINC": "InterestUSOblg",
    "FFIT161.CGEXCL": "CapitalGain",
    "FFIT161.PRIORBON": "BonusDepreciationAdj",
    "FFIT161.SUBTOTAL": "TotalAdditions",
    "FFIT161.VTTAXINC": "VTTaxableIncome",
    "FFIT161.VTTAX2": "VTTaxSch",
    "FFIT161.ADDVT": "AddToVtTax",
    "FFIT161.SUBVT": "SubtractionstoVtTax",
    "FFIT161.ADDSUB": "VTIncomeTax",
    "FFIT161.INCADJ": "IncomeAdjustment",
    "FFIT161.ADJTAX": "AdjustedTax",
    "FFIT161.OTHSTCR": "OtherStatesCredit",
    "FFIT161.TOTVTTAX": "TotalVtTaxes",
    "FFIT161.VTTAXWH": "VTTaxWithheld",
    "FFIT161.ESTTXPMT": "EstimatedPayment",
    "FFIT161.VTREWH": "RewWithholding",
    "FFIT161.NRPMTS": "BusEntityPayments",
    "FFIT161.OPMTAPPL": "OverPmtApplied",
    "FFIT161.TOTALPMT": "TotalPayments",
    "FFIT161.OVRPMT": "OverpaymentAmount",
    "FFIT161.OPMTCRED": "OverpmtCreditedNxtYr",
    "FFIT161.OPMTREF": "RefundAmount",
    "FFIT161.BALDUE": "BalanceDueWithReturn",
    "FFIT161.DPTYES": "DisclosureInd",
    "FFIT161.SIGPHONE": "PhoneNumber",
    }

mef = {


    "Estate": "Indicates if taxpayer filed for Estate",
    "Trust": "Indicates if taxpayer filed for Trust",
    "RevocableTrust": "Indicates if taxpayer filed for revocable Trust",
    "IrrevocableTrust": "Indicates if taxpayer filed for Irrevocable Trust",
    "ExtendedRtn": "Indicates if extension was filed for this return",
    "AmendedReturn": "Indicates if this return is an amended return",
    "FinalRtn": "Indicates if this will be taxpayer last filing",
    "DateOfDeath": "Date of Death",
    "StateDomicileAtDeath": "State of Domicle At death and/or creation of trust",
    "NonResdeBenef": "Where distributions reported to nonresident beneficiaries",
    "NoVtMuni": "Did the estate or trust have non-VT municipal bond Inocme",
    "PresFutBenSkip": "Any present or future trust beneficiaries skip persons",
    "QualSettlefnd": "Qualified Settlesment Fund",
    "FederalTaxableIncome": "Federal Taxable Income",
    "NonVtIncome": "Income from non VT state and local obligations",
    "BonusDepreciation": "Bonus Depreciation",
    "StateLocalTaxesOv5k": "State Local, Taxes over 5,000",
    "FedTaxableWithAdd": "Federal Taxable Income with Additions",
    "InterestUSOblg": "United States Government Interest",
    "CapitalGain": "Capital Gain Exclusion",
    "BonusDepricationAdj": "Adjustment for prior years bonus depriciation",
    "TotalAdditions": "Add lines 4a-4c",
    "VTTaxableIncome": "VT Taxable Income",
    "VTTaxSch": "Tax from Tax Rate Schedule",
    "AddToVtTax": "Additions to VT Tax",
    "SubtractionstoVtTax": "Subtractions To VT Tax",
    "VtIncomeTax": "Vermont Tax with Addition and Subtractions",
    "IncomeAdjustment": "Income Adjustment",
    "Adjusted": "Tax Adjusted Tax",
    "OtherStatesCredit": "Other States Credit",
    "TotalVtTaxes": "Total VT Taxes",
    "VTTaxWithheld": "Total VT Tax Withheld",
    "EstimatedPayment": "Estimated Tax or Extension Payments",
    "RewWithholding": "VT Real Estate Withholding",
    "BusEntityPayments": "Business Entity Payments for Nonresident Partner, Member or Shareholder",
    "OverPmtApplied": "Overpayment Applied",
    "TotalPayments": "Total Payments and credits",
    "OverpaymentAmount": "Overpayment",
    "OverpmtCreditedNxtYr": "Refund to be credited to next year",
    "RefundAmount": "Refund Amount",
    "BalanceDueWithReturn": "Amount you Owe",

    "DisclosureInd": "Check if authorizing Disclosure of Return Information",
    "PhoneNumber": "Taxpayer's Phone Number",
    "ForeignPhoneNumber": "Taxpayer's Phone Number",

    "Sch162Line1": "Smaller of Line 18a(2) or 19(2) Federal Form Schedule D",
    "Sch162Line2a": "Line 18b(2) from Schedule D",
    "Sch162Line2b": "Line 18c(2) from Schedule D",
    "Sch162Line3": "Add Lines 2a and 2b",
    "Sch162Line4": "Subtract Line 3 from Line 1",
    "Sch162Line5a": "Line 4g from Form 4952",
    "Sch162Line5b": "Line 4e from Form 4952",
    "Sch162Line5c": "Multiply Line 5a by Line 5b",
    "Sch162Line5d": "Line 4b from Form 4952",
    "Sch162Line5e": "Line 4e from Form 4952",
    "Sch162Line6": "Add Lines 5d and 5e",
    "Sch162Line7": "Divide Line 5c by Line 6",
    "Sch162Line8": "Subtract Line 7 from Line 4",
    "Sch162Line9": "Enter smaller of Line 8 or $5,000",
    "Sch162Line10": "Enter amount from Part I, Line 4",
    "Sch162AdjCapGain": "Amount of adjusted net capital gain from sale of assets",
    "Sch162Assets": "Subtract Line 11 from Line 10",
    "Sch162RealEstate": "Real estate or portion used as residence",
    "Sch162DepProp": "Depreciable personal property",
    "Sch162StockBond": "Stocks or bonds",
    "Sch162Line14": "Add Lines 13a through 13c",
    "Sch162Line15": "Subtract Line 14 from Line 12",
    "Sch162Line16": "Enter amount from Part I, Line 7 or recomputed Federal Form 4952",
    "Sch162Line17": "Subtract Line 16 from Line 15",
    "Sch162Line18": "Multiply Line 17 by 40%",
    "Sch162Line19": "Enter greater of Line 9 or Line 18",
    "Sch162Line20": "FIT Line 1 x 0.4",
    "Sch162GainExclusion": "Enter smaller of Line 19 or Line 20",

    "TotalLocalStateOblig": "Total Interest and Dividend Income from all State and Local Obligations",
    "VTLocalStateOblig": "Interest and Dividends from VT Obligations",
    "NonVTLocalStateOblig": "Income from Non VT State and Local Obligations",
    "TaxLumpDist": "Total Lump sum distributions",
    "RecaptureFedInvCrd": "Recapture Federal Investment Credit",
    "TotalAdditions": "Total Additions",
    "InvestVTBasedCredit": "Charitable Housing Amount Applied Current Year",
    "MultiplybyPercentage": "Multiply line 2a by 24%",
    "ResDevCredit": "Reseach and Development Credi",
    "TotalSubFromVTTax": "Total Subtractions from VT Tax",

    "Federal": "Portion",
    "Vermont": "Portion",
    "InterestIncome": "Interest Income",
    "TotalOrdinaryDiv": "Total Ordinary Dividends",
    "BusinessIncome": "Business Income or Loss",
    "CapitalGain": "Capital Gain or Loss",
    "RentsRoyalEstTrusts": "Rents, Royalties, Estates and Trusts",
    "FarmIncome": "Farm Income",
    "OrdinaryGain": "Ordinary Gain or Loss",
    "Other": "Other Income",
    "TotalIncome": "Total Income",
    "AdjPercentage": "Adjustment Percentage",
    "ResidentState": "State of Residence",
    "ResidentCanaidanProvCountry": "Canadian province or country",
    "ResidentFromDate": "Resident from date",
    "ResidentToDate": "Resident to date",


    "NameOtherState": "name of other State",
    "NameCanadianProv": "Name of Canadian province",
    "IncomeTaxableToBoth": "Total Income Taxable in VT and Other state/province",
    "BonusDepreciationAdd": "Bonue Depreciation Add back",
    "NonVTObligations": "Non-VT State/local Obligations",
    "Sch167AddBack": "Add lines 2-4",
    "BonusDepreciationSub": "Bonus Depreciation Subtraction",
    "InterestIncome": "US Government Interest Income",
    "Sch167Sum": "Add lines 6 and 7",
    "ModTotalInc": "Modified Total Income",
    "TotalIncome": "Total Income",
    "NonVtObligations": "Non VT Obligations",
    "BonusDepAdd": "Bonus Depreciation FI161 Line 2b",
    "Sch167Add": "Add lines 10-12",
    "USGovInterest": "US Gov Interest",
    "BonusDepSub": "Bonus Depreciation FI161 Line 4c",
    "Sch167AddTotal": "add lines 14 and 15",
    "Sch167Subtract": "Subtract line 16 from 13",
    "VTIncomeTax": "VT Income Tax",
    "CompTaxCredit": "Computed tax credit",
    "NetTaxPaidToOtherState": "Income Tax paid to other state or province",
    "CreditTaxPaidOtherState": "VT Credit for tax paid to another state",


    "FirstName": "Individual First name",
    "MiddleInitial": "Individual middle initial",
    "LastName": "Individual last name",
    "Ssn": "Social Security Number",
    "AddressLine1Txt": "line 1",
    "AddressLine1Txt": "line 2",
    "CityNm": "city",
    "StateAbbreviationCd": "state",
    "ZipCd": "zip",
    "CountryCd": "Country",
    "ProvinceOrStateNm": "Province or state",
    "ForeignPostalCd": "Foreign Postal Code",
    "VTResident": "Vermont Resident Exempt checkbox",
    "Nonresident": "Nonresident checkbox",
    "PercEntityIncorLoss": "Percentage of Entitys income or loss to this recipient",
    "FinalRtn": "Final Return checkbox",
    "BenifShareFedTaxInc": "Beneficiary's Share of Federal Taxable Income",
    "IntDivOtherStates": "Interest/dividends from Obligations of other states",
    "IntDivUsObl": "Interest/dividends from US Obligation",
    "InterestIncomeNr": "NonResident Interest Income",
    "DividendIncomeNr": "NonResident Dividend Income",
    "BusIncomeNr": "NonResident Business Income",
    "CapitalGainLossNr": "NonResident Capital Gain or Loss",
    "PtnrScorpLlcIncN": "NonResident Partnership, S Corp, LLC Income",
    "RentRoyEstTrustNr": "NonResident Rent, Royalties, Estates, Trusts",
    "FarmIncNr": "NonResident Farm Income",
    "OtherIncomeNr": "NonResident Other Income",
    "TotalNonresInc": "Total Nonresident Income",
    "NonresEstimatedPmts": "Total annual nonresidnet estimated payments allocated to this shareholder",
    "RealEstateWithholding": "Total annual real estate withholding payments allocated to this shareholder",
    }

